name: transcriber
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - pip:
      - streamlit
      - moviepy
      - pysrt
      - pydub
      - tqdm
      - opencv-python-headless
      - git+https://github.com/openai/whisper.git
      - openai
